### ISSUE TITLE
Numbering in newfloat environment is right-to-left

### ISSUE THREAD

**Issue by furihr** [persian-tex/xepersian#1]
Using the `newfloat` package, the numering of the <type>s is done in the opposite direction from tables, chapters, etc.

We had the same problem with `listings`, several months ago, which was fixed fairly quickly.

**Comment by furihr** [comment]
The MWE:
  
  \documentclass[12pt,a4paper]{report}

    \usepackage{newfloat}
    \DeclareFloatingEnvironment[
	fileext=lod,
	listname=فهرست نمودارها,
	name=نمودار,
	placement=tbhp,
    %     within=section,
    ]{diagram}
    \usepackage{xepersian}
    \settextfont{Nazli}
    \begin{document}
    \listofdiagrams
    \chapter{فصل اول}
    \chapter{فصل دوم}
    نمودار \ref{uml-Matrix}
    \begin{diagram}
    \centering
    %  \includegraphics[scale=0.5]{Matrix.pdf}
    \caption{\label{uml-Matrix}
    نمودار یوإم‌ال کلاس 
    \lr{\texttt{Matrix}}}
    \end{diagram}

    \end{document}

**Comment by persian-tex** [comment]
I just looked at this. You need to use `\DeclareFloatingEnvironment` after loading `xepersian` package because when the `bidi` package sees that `newfloat` package is loaded, it does some modifications to the package and therefore if you use `\DeclareFloatingEnvironment` before `bidi` package (`xepersian` package in your example), then `bidi` package changes have no effect.
